package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

type PointType string

const (
	pointTypeBool   PointType = "bool"
	pointTypeInt16  PointType = "int16"
	pointTypeUint16 PointType = "uint16"
)

var (
	errPointNotFound    = errors.New("point not found")
	errPointNotWritable = errors.New("point is not writable from the page")
	pointAddressPattern = regexp.MustCompile(`^D([0-9]+)(?:\.([0-9]+))?$`)
)

type validationError struct {
	message string
}

func (e validationError) Error() string {
	return e.message
}

func invalidPoint(format string, args ...any) error {
	return validationError{message: fmt.Sprintf(format, args...)}
}

// Point is the JSON definition persisted in the points file.
type Point struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Type        PointType `json:"type"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
	Writable    bool      `json:"writable"`
}

// PointInput is used for create and update requests. IDs are generated by the
// server and are never accepted from the page.
type PointInput struct {
	Name        string    `json:"name"`
	Type        PointType `json:"type"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
	Writable    bool      `json:"writable"`
}

type PointView struct {
	Point
	Value     any       `json:"value"`
	UpdatedAt time.Time `json:"updatedAt"`
	Source    string    `json:"source"`
}

type pointLocation struct {
	register uint16
	bit      int
	isBit    bool
}

type pointRecord struct {
	Point
	location pointLocation
}

type pointState struct {
	updatedAt time.Time
	source    string
}

type simulatorEvent struct {
	Type   string      `json:"type"`
	Points []PointView `json:"points,omitempty"`
}

type eventBroker struct {
	mu          sync.Mutex
	subscribers map[chan simulatorEvent]struct{}
}

func (b *eventBroker) subscribe() (<-chan simulatorEvent, func()) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.subscribers == nil {
		b.subscribers = make(map[chan simulatorEvent]struct{})
	}
	channel := make(chan simulatorEvent, 32)
	b.subscribers[channel] = struct{}{}
	return channel, func() {
		b.mu.Lock()
		delete(b.subscribers, channel)
		b.mu.Unlock()
	}
}

func (b *eventBroker) publish(event simulatorEvent) {
	b.mu.Lock()
	defer b.mu.Unlock()
	for channel := range b.subscribers {
		select {
		case channel <- event:
		default:
			// The page will fetch the current state again on its next event.
		}
	}
}

// PointManager owns point definitions and maps their views onto the server's
// in-memory holding registers. Definitions persist, while register values do
// not.
type PointManager struct {
	mu     sync.RWMutex
	server *Server
	file   string
	points []pointRecord
	states map[string]pointState
	nextID uint64
	events eventBroker
}

func NewPointManager(file string, server *Server) (*PointManager, error) {
	if strings.TrimSpace(file) == "" {
		return nil, fmt.Errorf("points file is required")
	}
	if server == nil {
		return nil, fmt.Errorf("server is required")
	}
	manager := &PointManager{
		server: server,
		file:   file,
		states: make(map[string]pointState),
		nextID: uint64(time.Now().UnixNano()),
	}
	if err := manager.Reload(); err != nil {
		return nil, err
	}
	server.SetRegisterChangeHandler(manager.onRegisterChange)
	return manager, nil
}

// Reload reads and validates the current JSON definitions. It intentionally
// changes definitions only; holding registers remain untouched.
func (m *PointManager) Reload() error {
	points, err := readPointDefinitions(m.file)
	if err != nil {
		return err
	}
	records, err := normalizeRecords(points, true)
	if err != nil {
		return fmt.Errorf("validate points file: %w", err)
	}

	now := time.Now().UTC()
	m.mu.Lock()
	states := make(map[string]pointState, len(records))
	for _, record := range records {
		state, ok := m.states[record.ID]
		if !ok || !sameLocation(record.location, findLocation(m.points, record.ID)) {
			state = pointState{updatedAt: now, source: "definition"}
		}
		states[record.ID] = state
	}
	m.points = records
	m.states = states
	m.mu.Unlock()
	m.events.publish(simulatorEvent{Type: "definitions"})
	return nil
}

func (m *PointManager) List() []PointView {
	m.mu.RLock()
	records := append([]pointRecord(nil), m.points...)
	states := make(map[string]pointState, len(m.states))
	for id, state := range m.states {
		states[id] = state
	}
	m.mu.RUnlock()

	views := make([]PointView, 0, len(records))
	for _, record := range records {
		views = append(views, m.viewForValue(record, m.server.ReadRegister(record.location.register), states[record.ID]))
	}
	return views
}

func (m *PointManager) Get(id string) (PointView, error) {
	m.mu.RLock()
	record, state, ok := m.recordByIDLocked(id)
	m.mu.RUnlock()
	if !ok {
		return PointView{}, errPointNotFound
	}
	return m.viewForValue(record, m.server.ReadRegister(record.location.register), state), nil
}

func (m *PointManager) Add(input PointInput) (PointView, error) {
	record, err := normalizeRecord(Point{
		Name:        input.Name,
		Type:        input.Type,
		Description: input.Description,
		Address:     input.Address,
		Writable:    input.Writable,
	}, false)
	if err != nil {
		return PointView{}, err
	}

	now := time.Now().UTC()
	m.mu.Lock()
	record.ID = m.newIDLocked()
	if err := validateUnique(m.points, record, -1); err != nil {
		m.mu.Unlock()
		return PointView{}, err
	}
	candidate := append(append([]pointRecord(nil), m.points...), record)
	if err := m.saveLocked(candidate); err != nil {
		m.mu.Unlock()
		return PointView{}, err
	}
	m.points = candidate
	m.states[record.ID] = pointState{updatedAt: now, source: "definition"}
	state := m.states[record.ID]
	m.mu.Unlock()

	m.events.publish(simulatorEvent{Type: "definitions"})
	return m.viewForValue(record, m.server.ReadRegister(record.location.register), state), nil
}

func (m *PointManager) Update(id string, input PointInput) (PointView, error) {
	record, err := normalizeRecord(Point{
		ID:          id,
		Name:        input.Name,
		Type:        input.Type,
		Description: input.Description,
		Address:     input.Address,
		Writable:    input.Writable,
	}, true)
	if err != nil {
		return PointView{}, err
	}

	now := time.Now().UTC()
	m.mu.Lock()
	index := -1
	for currentIndex, current := range m.points {
		if current.ID == id {
			index = currentIndex
			break
		}
	}
	if index == -1 {
		m.mu.Unlock()
		return PointView{}, errPointNotFound
	}
	if err := validateUnique(m.points, record, index); err != nil {
		m.mu.Unlock()
		return PointView{}, err
	}
	candidate := append([]pointRecord(nil), m.points...)
	candidate[index] = record
	if err := m.saveLocked(candidate); err != nil {
		m.mu.Unlock()
		return PointView{}, err
	}
	m.points = candidate
	m.states[id] = pointState{updatedAt: now, source: "definition"}
	state := m.states[id]
	m.mu.Unlock()

	m.events.publish(simulatorEvent{Type: "definitions"})
	return m.viewForValue(record, m.server.ReadRegister(record.location.register), state), nil
}

func (m *PointManager) Delete(id string) error {
	m.mu.Lock()
	index := -1
	for currentIndex, current := range m.points {
		if current.ID == id {
			index = currentIndex
			break
		}
	}
	if index == -1 {
		m.mu.Unlock()
		return errPointNotFound
	}
	candidate := append([]pointRecord(nil), m.points[:index]...)
	candidate = append(candidate, m.points[index+1:]...)
	if err := m.saveLocked(candidate); err != nil {
		m.mu.Unlock()
		return err
	}
	m.points = candidate
	delete(m.states, id)
	m.mu.Unlock()
	m.events.publish(simulatorEvent{Type: "definitions"})
	return nil
}

func (m *PointManager) SetValue(id string, raw json.RawMessage) (PointView, error) {
	m.mu.RLock()
	record, _, ok := m.recordByIDLocked(id)
	m.mu.RUnlock()
	if !ok {
		return PointView{}, errPointNotFound
	}
	if !record.Writable {
		return PointView{}, errPointNotWritable
	}

	switch record.Type {
	case pointTypeBool:
		var value bool
		if err := json.Unmarshal(raw, &value); err != nil {
			return PointView{}, invalidPoint("bool point value must be true or false")
		}
		mask := uint16(1) << uint(record.location.bit)
		orMask := uint16(0)
		if value {
			orMask = mask
		}
		m.server.MaskWriteRegisterFromUI(record.location.register, ^mask, orMask)
	case pointTypeInt16:
		var value int64
		if err := json.Unmarshal(raw, &value); err != nil || value < -32768 || value > 32767 {
			return PointView{}, invalidPoint("int16 point value must be an integer between -32768 and 32767")
		}
		m.server.WriteRegisterFromUI(record.location.register, uint16(int16(value)))
	case pointTypeUint16:
		var value uint64
		if err := json.Unmarshal(raw, &value); err != nil || value > 65535 {
			return PointView{}, invalidPoint("uint16 point value must be an integer between 0 and 65535")
		}
		m.server.WriteRegisterFromUI(record.location.register, uint16(value))
	default:
		return PointView{}, invalidPoint("unsupported point type %q", record.Type)
	}
	return m.Get(id)
}

func (m *PointManager) SubscribeEvents() (<-chan simulatorEvent, func()) {
	return m.events.subscribe()
}

func (m *PointManager) onRegisterChange(address, value uint16, source string) {
	now := time.Now().UTC()
	m.mu.Lock()
	views := make([]PointView, 0)
	for _, record := range m.points {
		if record.location.register != address {
			continue
		}
		state := pointState{updatedAt: now, source: source}
		m.states[record.ID] = state
		views = append(views, m.viewForValue(record, value, state))
	}
	m.mu.Unlock()
	if len(views) > 0 {
		m.events.publish(simulatorEvent{Type: "values", Points: views})
	}
}

func (m *PointManager) recordByIDLocked(id string) (pointRecord, pointState, bool) {
	for _, record := range m.points {
		if record.ID == id {
			return record, m.states[id], true
		}
	}
	return pointRecord{}, pointState{}, false
}

func (m *PointManager) newIDLocked() string {
	m.nextID++
	return fmt.Sprintf("point-%d", m.nextID)
}

func (m *PointManager) saveLocked(records []pointRecord) error {
	points := make([]Point, 0, len(records))
	for _, record := range records {
		points = append(points, record.Point)
	}
	data, err := json.MarshalIndent(points, "", "  ")
	if err != nil {
		return fmt.Errorf("encode point definitions: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(m.file, data, 0o644); err != nil {
		return fmt.Errorf("save point definitions: %w", err)
	}
	return nil
}

func readPointDefinitions(file string) ([]Point, error) {
	data, err := os.ReadFile(file)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read points file: %w", err)
	}
	var points []Point
	if err := json.Unmarshal(data, &points); err != nil {
		return nil, fmt.Errorf("decode points file: %w", err)
	}
	return points, nil
}

func normalizeRecords(points []Point, requireID bool) ([]pointRecord, error) {
	records := make([]pointRecord, 0, len(points))
	for _, point := range points {
		record, err := normalizeRecord(point, requireID)
		if err != nil {
			return nil, err
		}
		if err := validateUnique(records, record, -1); err != nil {
			return nil, err
		}
		records = append(records, record)
	}
	return records, nil
}

func normalizeRecord(point Point, requireID bool) (pointRecord, error) {
	point.ID = strings.TrimSpace(point.ID)
	if requireID && point.ID == "" {
		return pointRecord{}, invalidPoint("point id is required")
	}
	point.Name = strings.TrimSpace(point.Name)
	if point.Name == "" {
		return pointRecord{}, invalidPoint("point name is required")
	}
	location, address, err := parsePointAddress(point.Type, point.Address)
	if err != nil {
		return pointRecord{}, err
	}
	point.Address = address
	return pointRecord{Point: point, location: location}, nil
}

func parsePointAddress(pointType PointType, text string) (pointLocation, string, error) {
	match := pointAddressPattern.FindStringSubmatch(strings.TrimSpace(text))
	if match == nil {
		return pointLocation{}, "", invalidPoint("point address must use D<number> or D<number>.<0..15>")
	}
	register, err := strconv.ParseUint(match[1], 10, 16)
	if err != nil {
		return pointLocation{}, "", invalidPoint("D register must be between 0 and 65535")
	}
	location := pointLocation{register: uint16(register)}
	if pointType == pointTypeBool {
		if match[2] == "" {
			return pointLocation{}, "", invalidPoint("bool point address must use D<number>.<0..15>")
		}
		bit, err := strconv.ParseUint(match[2], 10, 8)
		if err != nil || bit > 15 {
			return pointLocation{}, "", invalidPoint("bool point bit must be between 0 and 15")
		}
		location.bit = int(bit)
		location.isBit = true
		return location, fmt.Sprintf("D%d.%d", location.register, location.bit), nil
	}
	if pointType != pointTypeInt16 && pointType != pointTypeUint16 {
		return pointLocation{}, "", invalidPoint("point type must be bool, int16, or uint16")
	}
	if match[2] != "" {
		return pointLocation{}, "", invalidPoint("%s point address must use D<number>", pointType)
	}
	return location, fmt.Sprintf("D%d", location.register), nil
}

func validateUnique(records []pointRecord, candidate pointRecord, skip int) error {
	for index, record := range records {
		if index == skip {
			continue
		}
		if record.ID == candidate.ID && candidate.ID != "" {
			return invalidPoint("point id %q already exists", candidate.ID)
		}
		if strings.EqualFold(record.Name, candidate.Name) {
			return invalidPoint("point name %q already exists", candidate.Name)
		}
		if record.Type == candidate.Type && record.Address == candidate.Address {
			return invalidPoint("point type %s at address %s already exists", candidate.Type, candidate.Address)
		}
	}
	return nil
}

func sameLocation(left, right pointLocation) bool {
	return left.register == right.register && left.bit == right.bit && left.isBit == right.isBit
}

func findLocation(records []pointRecord, id string) pointLocation {
	for _, record := range records {
		if record.ID == id {
			return record.location
		}
	}
	return pointLocation{register: ^uint16(0), bit: -1}
}

func (m *PointManager) viewForValue(record pointRecord, registerValue uint16, state pointState) PointView {
	var value any
	switch record.Type {
	case pointTypeBool:
		value = registerValue&(uint16(1)<<uint(record.location.bit)) != 0
	case pointTypeInt16:
		value = int16(registerValue)
	case pointTypeUint16:
		value = registerValue
	}
	return PointView{
		Point:     record.Point,
		Value:     value,
		UpdatedAt: state.updatedAt,
		Source:    state.source,
	}
}
